meta:
  generated_at: "{{ now }}"
  notes: |
    Tracks authoritative guidance sources used by the policy indexer.
sources:
  - id: pod_security_standards
    description: "Kubernetes Pod Security Standards"
    url: "https://raw.githubusercontent.com/kubernetes/website/main/content/en/docs/concepts/security/pod-security-standards.md"
    extract:
      format: "markdown"
      sections:
        - heading: "Restricted"
  - id: cis_kubernetes
    description: "CIS Kubernetes Benchmark v1.24 (excerpt)"
    path: "docs/policy_guidance/static/cis_kubernetes.md"
  - id: kyverno_best_practices
    description: "Kyverno best-practice policies"
    path: "docs/policy_guidance/static/kyverno_best_practices.md"
